spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.107/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  #返回对象为空不进行返回
  jackson:
    default-property-inclusion: non_null
#增加访问路径/sell
server:
  context-path: /sell
